#!/bin/sh
# Build script generated by Query Point Manager.
# If you plan to modify this, please be aware that:
# - You MUST maintain the current command line interface:
# -- slot 1: docker tag, defaulting to my-app
# -- slot 2: target platform, defaulting to empty string
# - Any extra options you add *will not be used* (so don't add them). Remember that this script will be used in automated training runs (according to the current CLI convention), as opposed to a utility script intended for human developers.

DOCKER_TAG=${1:-my-app}
DOCKER_DEFAULT_PLATFORM=$2

if [ -n "$DOCKER_DEFAULT_PLATFORM" ]; then
    docker build --platform "$DOCKER_DEFAULT_PLATFORM" -t "$DOCKER_TAG" .
else
    docker build -t "$DOCKER_TAG" .
fi